name: ThreatNet-Topic
version: 0.01
abstract: An object representation of a ThreatNet channel topic
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.82
requires:
  perl: 5.005
  URI: 1.26
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
